---
name: Bug Report
description: Create a report to help us reproduce and fix the bug
labels: [bug]
assignees:
  - kmezynski

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been
        already addressed by searching through [Ansible issues](https://github.com/ansible/ansible/issues?page=1&q=is%3Aissue),
        [Molecule issues](https://github.com/ansible-community/molecule/issues?page=1&q=is%3Aissue)
        and [the existing and past issues](https://github.com/kmezynski/ansible-role-pyenv/issues?q=is%3Aissue).
  - type: textarea
    attributes:
      label: Describe the bug
      description: >
        Please provide a clear and concise description of what the bug is.

        If relevant, add a minimal setup example so that bug can be reproduced
        by running the code.

        Please also paste or describe the results you observe instead of the
        expected results. If you observe an error, please paste the error
        message including the **full** log. It may be relevant to wrap error
        messages in ```` ```triple quotes blocks``` ````.
      placeholder: |
        A clear and concise description of what the bug is.

        ```sh
        # Sample commands to reproduce the problem
        ```

        ```
        The error message you got, with the full log.
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the expected behaviour
      description: >
        Please provide a clear and concise description of expected behaviour.
      placeholder: |
        A clear and concise description of expected behaviour.
    validations:
      required: true
  - type: input
    attributes:
      label: OS specs
      placeholder: distro x.y.z arch
    validations:
      required: true
  - type: input
    attributes:
      label: Ansible version
      placeholder: ansible x.y.z
    validations:
      required: true
  - type: input
    attributes:
      label: Molecule version
      placeholder: molecule x.y.z
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks for contributing 🎉!
