---
name: Feature request
description: Submit a proposal/request for a new feature for this project
labels: [enhancement]
assignees:
  - kmezynski

body:
  - type: textarea
    attributes:
      label: The feature, motivation and pitch
      description: >
        A clear and concise description of the feature proposal. Please outline
        the motivation for the proposal. Is your feature request related to a
        specific problem? If this is related to another GitHub issue, please
        link here too.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: >
        Add any other context or screenshots about the feature request.
  - type: markdown
    attributes:
      value: Thanks for contributing 🎉!
